export type Doctor = {
  id: number
  name: string
  designation: string
  specialization: string
  email: string
  mobile: string
  officePhone?: string
  room?: string
  photo: string
  category: "doctor" | "nurse"
}

export const doctors: Doctor[] = [
  {
    id: 1,
    name: "ডা. জুনায়েদ আব্দুল কাইয়ূম",
    designation: "উপজেলা স্বাস্থ্য ও পরিবার পরিকল্পনা কর্মকর্তা",
    specialization: "Administration",
    email: "junaidaq26@gmail.com",
    mobile: "০১৮১৯১৩৫৬৪২",
    room: "১২৭",
    photo: "/doctors/doctor-01.jpeg",
    category: "doctor",
  },
  {
    id: 2,
    name: "ডা: মোসাম্মৎ নায়লা হোসেন",
    designation: "Jr. Consultant (Gyn & Obs)",
    specialization: "Gynecology & Obstetrics",
    email: "drnailasharif@gmail.com",
    mobile: "০১৭১৮১৩৪২৪৯",
    photo: "/doctors/doctor-02.png",
    category: "doctor",
  },
  {
    id: 3,
    name: "ডাঃ এ, কে, এম, জাহাঙ্গীর হোসেন",
    designation: "জুনিয়র কনসালটেন্ট পিডিয়াট্রিক",
    specialization: "Pediatrics",
    email: "jhossain335@gmail.com",
    mobile: "০১৭১৬৯৪৯৩৭৮",
    room: "২০৩",
    photo: "/doctors/doctor-03.png",
    category: "doctor",
  },
  {
    id: 4,
    name: "ডা. নোমান আল সিফাত প্রান্ত",
    designation: "মেডিকেল অফিসার",
    specialization: "Medicine",
    email: "sifatpranto74@gmail.com",
    mobile: "০১৮৬৪০৭৪৪৯১",
    photo: "/doctors/doctor-04.png",
    category: "doctor",
  },
  {
    id: 5,
    name: "ডা. হুমায়ুন আহমেদ নূর",
    designation: "মেডিকেল অফিসার",
    specialization: "Medicine",
    email: "humayunnur2016@gmail.com",
    mobile: "০১৭১০৫১০৮২৭",
    room: "১১৮",
    photo: "/doctors/doctor-05.png",
    category: "doctor",
  },
  {
    id: 6,
    name: "ডাঃ মেহেদী হাসান",
    designation: "ডেন্টাল সার্জন",
    specialization: "Dental",
    email: "mhasanssmc2020@gmail.com",
    mobile: "০১৮৪০০৯৪৭০৫",
    room: "১০৪",
    photo: "/doctors/doctor-06.png",
    category: "doctor",
  },
  {
    id: 7,
    name: "ডা. মাহমুদা আক্তার মলি",
    designation: "Asstt. Surgeon / Medical Officer",
    specialization: "Orthopedics & Traumatology",
    email: "dr.mahmuda26@gmail.com",
    mobile: "০১৩০১৩৬৮৩১৯",
    room: "১০৫",
    photo: "/doctors/doctor-07.jpeg",
    category: "doctor",
  },
  {
    id: 8,
    name: "ডাঃ মোহাম্মাদ তানভীর ইবনে কাদের",
    designation: "Medical Officer (Homeopathic)",
    specialization: "Homeopathic",
    email: "drtanvirbhms@gmail.com",
    mobile: "০১৯৩৭৯১৯১০৯",
    room: "১১০",
    photo: "/doctors/doctor-08.jpg",
    category: "doctor",
  },
  {
    id: 9,
    name: "ডা. ফারহানা আক্তার",
    designation: "মেডিকেল অফিসার",
    specialization: "Medicine",
    email: "dr.fmumu@gmail.com",
    mobile: "০১৭৭০৯৬৯৮০৪",
    photo: "/doctors/doctor-09.png",
    category: "doctor",
  },
  {
    id: 10,
    name: "ডা. জয়দেব বর্মন",
    designation: "Asstt. Surgeon / Medical Officer",
    specialization: "Pediatrics",
    email: "joydebbormon715@gmail.com",
    mobile: "০১৯৬৮৪০৩০৭২",
    room: "১০৮",
    photo: "/doctors/doctor-10.jpg",
    category: "doctor",
  },
  {
    id: 11,
    name: "ডা. ফারহানা সুলতানা",
    designation: "ইমার্জেন্সি মেডিকেল অফিসার",
    specialization: "Emergency Medicine",
    email: "farhanarini733@gmail.com",
    mobile: "০১৫১৬০৭৭০৩০",
    room: "১০৫",
    photo: "/doctors/doctor-11.jpg",
    category: "doctor",
  },
  {
    id: 12,
    name: "ডা. শেখ রাসেল আল মেহেদী",
    designation: "Asstt. Surgeon / Medical Officer",
    specialization: "Ophthalmology",
    email: "raselmehedi999@gmail.com",
    mobile: "০১৭০০৬৩৮৯৪৯",
    room: "১০১",
    photo: "/doctors/doctor-12.jpg",
    category: "doctor",
  },
  {
    id: 13,
    name: "ডা. সৌমিক পাল",
    designation: "Asstt. Surgeon / Medical Officer",
    specialization: "Gynecology & Obstetrics",
    email: "soumikpaul145@gmail.com",
    mobile: "০১৭৬৭১২৫০০২",
    room: "১০৮",
    photo: "/doctors/doctor-13.jpg",
    category: "doctor",
  },
  {
    id: 14,
    name: "ডা. ফারজানা ইয়াসমিন",
    designation: "Asstt. Surgeon / Medical Officer",
    specialization: "Medicine",
    email: "farzanayeasmin913@gmail.com",
    mobile: "০১৭৩৫১৫৯৫৫২",
    room: "১০৫",
    photo: "/doctors/doctor-14.jpg",
    category: "doctor",
  },
  {
    id: 15,
    name: "ডাঃ ফাহাদ রহমান",
    designation: "মেডিকেল অফিসার",
    specialization: "Medicine",
    email: "fahadrahman731.fr@gmail.com",
    mobile: "০১৭৩৬৫৫৫৯৮০",
    photo: "/doctors/doctor-15.png",
    category: "doctor",
  },
  {
    id: 16,
    name: "ডা. সুস্মিতা কর্মকার",
    designation: "Asstt. Surgeon / Medical Officer",
    specialization: "Surgery",
    email: "sushmitakarmakar39@gmail.com",
    mobile: "০১৭৪৪৭০৯২৮৪",
    room: "১০৫",
    photo: "/doctors/doctor-18.jpeg",
    category: "doctor",
  },
  {
    id: 17,
    name: "মেহেদী হাসান শিবলী",
    designation: "ডেন্টাল সার্জন",
    specialization: "Dental",
    email: "mehedihs669@gmail.com",
    mobile: "০১৯৯৯২৭১২৬৩",
    room: "১০৪",
    photo: "/doctors/doctor-19.jpg",
    category: "doctor",
  },
]